In [1]:
import pandas as pd
import numpy as np

In [2]:
shopping = pd.read_csv('/AnalysoinninPerusteetPython/shopping_behavior_updated.csv')

In [3]:
shopping.loc[(shopping['Age'] == 18.0)]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
24,25,18,Male,Jacket,Outerwear,22,Florida,M,Green,Fall,2.9,Yes,Store Pickup,Yes,Yes,16,Debit Card,Weekly
25,26,18,Male,Hoodie,Clothing,25,Texas,M,Silver,Summer,3.6,Yes,Express,Yes,Yes,14,PayPal,Annually
72,73,18,Male,Dress,Clothing,26,Georgia,M,Olive,Winter,2.9,Yes,Store Pickup,Yes,Yes,21,Bank Transfer,Every 3 Months
228,229,18,Male,Socks,Clothing,79,New Hampshire,M,White,Spring,2.9,Yes,Store Pickup,Yes,Yes,11,Credit Card,Annually
357,358,18,Male,Belt,Accessories,56,Arkansas,M,Olive,Spring,4.0,Yes,Standard,Yes,Yes,16,Credit Card,Bi-Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3610,3611,18,Female,Jacket,Outerwear,86,Texas,XL,Green,Fall,4.8,No,2-Day Shipping,No,No,23,Bank Transfer,Fortnightly
3714,3715,18,Female,Hat,Accessories,31,New York,S,Peach,Winter,3.9,No,Express,No,No,35,Credit Card,Weekly
3725,3726,18,Female,Dress,Clothing,100,Oklahoma,S,Turquoise,Winter,4.4,No,Next Day Air,No,No,2,PayPal,Annually
3806,3807,18,Female,Boots,Footwear,71,Missouri,M,Teal,Spring,3.0,No,Standard,No,No,41,PayPal,Weekly
3868,3869,18,Female,Dress,Clothing,29,Maryland,XL,Magenta,Winter,3.3,No,2-Day Shipping,No,No,9,Cash,Annually

In [4]:
ages = [18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70]
# to divide them into bins of 20 - 25, 26 - 35 , 36- 45 & > 46
# we will use cut function
bins = [18,30,45,55,70 ]
age_bins = pd.cut(ages,bins)
# to chek the categories
age_bins.categories
#lets count the values for each bin
pd.value_counts(age_bins)

C:\Users\hippo\AppData\Local\Temp\ipykernel_21224\1231180679.py:9: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_bins)

(30, 45]    15
(55, 70]    15
(18, 30]    12
(45, 55]    10
Name: count, dtype: int64

In [5]:
age_bins1 = pd.cut(ages, bins, right=False)
age_bins1.categories

IntervalIndex([[18, 30), [30, 45), [45, 55), [55, 70)], dtype='interval[int64, left]')

In [6]:
gnames = ['YoundAdult', 'Adult','MiddleAged','Elderly']
bins_labels = pd.cut(ages, bins, labels=gnames)
bins_labels.categories

Index(['YoundAdult', 'Adult', 'MiddleAged', 'Elderly'], dtype='object')

In [7]:
print(bins_labels)

[NaN, 'YoundAdult', 'YoundAdult', 'YoundAdult', 'YoundAdult', ..., 'Elderly', 'Elderly', 'Elderly', 'Elderly', 'Elderly']
Length: 53
Categories (4, object): ['YoundAdult' < 'Adult' < 'MiddleAged' < 'Elderly']

In [8]:
shopping['Age']

0       55
1       19
2       50
3       21
4       45
        ..
3895    40
3896    52
3897    46
3898    44
3899    52
Name: Age, Length: 3900, dtype: int64

In [9]:
shopping

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [11]:
shopping = {'Age':[18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70]}
df_shopping = pd.DataFrame(shopping)
# to divide them into bins of 20 - 25, 26 - 35 , 36- 45 & > 46, define the bin edges
bins = [18,30,40,50,60,70]

# lets create lables for each bin
labels = ['YoungAdult', 'Adult', 'MiddleAged', 'Elderly', 'Retired']

# we will use cut function to bin
df_shopping['AgeGroup'] = pd.cut(df_shopping['Age'], bins=bins, labels=labels, right=False)

# Get the list of categories
categories_list = df_shopping['AgeGroup'].cat.categories.tolist()
print(categories_list)

# Count the values in each bin
bin_counts = df_shopping['AgeGroup'].value_counts()
print(bin_counts)

['YoungAdult', 'Adult', 'MiddleAged', 'Elderly', 'Retired']
AgeGroup
YoungAdult    12
Adult         10
MiddleAged    10
Elderly       10
Retired       10
Name: count, dtype: int64

In [12]:
categories_list = df_shopping['AgeGroup'].cat.categories.tolist()
print(categories_list)

['YoungAdult', 'Adult', 'MiddleAged', 'Elderly', 'Retired']